name: kloner
description: "Android app cloner"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0

  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  permission_handler: ^11.3.1
  device_apps: ^2.1.1
  device_info_plus: ^10.1.2
  encrypt: ^5.0.3
  crypto: ^3.0.5

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
