name: kloner
description: "Android app cloner"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.0
  installed_apps: 2.1.0
  flutter_screenutil: ^5.9.3

  flutter_secure_storage: ^10.0.0
  local_auth: ^3.0.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  encrypt: ^5.0.3
  crypto: ^3.0.7

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  dartz: ^0.10.1
  shared_preferences: ^2.5.4
  shizuku_api: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
